version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      github-actions-major:
        patterns:
          - '*'
        update-types:
          - major
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      flutter-pub-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      flutter-pub-major:
        patterns:
          - '*'
        update-types:
          - major
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - flutter
